[package]
name = "example-otel-jaeger"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "example-otel-client"
path = "src/client.rs"

[[bin]]
name = "example-otel-server1"
path = "src/server1.rs"

[[bin]]
name = "example-otel-server2"
path = "src/server2.rs"

[dependencies]
salvo = { workspace = true, features = ["affix-state", "otel"] }
tokio = { workspace = true, features = ["macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
opentelemetry = { workspace = true, features = ["metrics"]  }
reqwest = { workspace = true }
prometheus = "0.13"
opentelemetry-prometheus.workspace = true
opentelemetry-http.workspace = true
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["http-proto", "tonic", "trace", "reqwest"] }